apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iam.authzServerFullname" . }}
  labels:
    {{- include "iam.authzServerLabels" . | nindent 4 }}
data:
  iam-authzserver.yaml: |
    {{- .Files.Get .Values.authzServer.configFile | nindent 4}}
