{{- if .Values.authzServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iam.authzServerFullname" . }}
  labels:
    {{- include "iam.authzServerLabels" . | nindent 4 }}
    {{- with .Values.authzServer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.authzServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.authzServer.service.type }}
  {{- with .Values.authzServer.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if eq "LoadBalancer" .Values.authzServer.service.type }}
  {{- with .Values.authzServer.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.authzServer.service.loadBalancerSourceRanges  }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.authzServer.service.ports.http }}
      targetPort: http
      {{- if (and (or (eq .Values.authzServer.service.type "NodePort") (eq .Values.authzServer.service.type "LoadBalancer")) (not (empty .Values.authzServer.service.nodePorts.http))) }}
      nodePort: {{ .Values.authzServer.service.nodePorts.http }}
      {{- end }}
      protocol: TCP
    - name: https
      port: {{ .Values.authzServer.service.ports.https }}
      targetPort: https
      {{- if (and (or (eq .Values.authzServer.service.type "NodePort") (eq .Values.authzServer.service.type "LoadBalancer")) (not (empty .Values.authzServer.service.nodePorts.https))) }}
      nodePort: {{ .Values.authzServer.service.nodePorts.https }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "iam.authzServerSelectorLabels" . | nindent 4 }}
{{- end }}
