# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

rpcserver: iam-apiserver.iam-system:8001 # iam-apiserver grpc 服务器地址和端口

client-ca-file: /var/run/iam/certificates/ca.crt

server:
  mode: release
  healthz: true
  middlewares: recovery,logger,secure,nocache,cors

insecure:
  bind-address: 0.0.0.0
  bind-port: 8010

secure:
  required: true
  bind-address: 0.0.0.0
  bind-port: 9443
  tls:
    cert-dir: /var/run/iam/certificates
    pair-name: tls

redis:
  host: redis-master.infra
  port: 6379
  password:

feature:
  enable-metrics: true
  profiling: true
