# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

server:
  mode: release # server mode: release, debug, test
  healthz: true # If enabled, the /healthz route is installed. default value is true
  middlewares: recovery,logger,secure,nocache,cors
  max-ping-count: 3
  static-locations: /etc/iam/template/*

grpc:
  bind-address: 0.0.0.0
  bind-port: 8001

insecure:
  bind-address: 0.0.0.0
  bind-port: 8000

secure:
  bind-address: 0.0.0.0
  bind-port: 8443
  tls:
    cert-dir: /var/run/iam/certificates
    pair-name: tls

mysql:
  host: mysql.infra:3306
  username: root
  password: WeCoding@2023
  database: iam_1
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

redis:
  host: redis-master.infra
  port: 6379
  password:

cache:
  type: redis
  options:
    host: redis-master.infra
    port: 6379
    password:

log:
  name: apiserver
  development: false
  level: info
  format: console
  enable-color: true
  disable-caller: false
  disable-stacktrace: false
  output-paths: /var/log/iam/iam-apiserver.log,stdout
  error-output-paths: /var/log/iam/iam-apiserver.error.log

feature:
  enable-metrics: true
  profiling: true

authentication:
  domain: wecoding.local
  jwtSecret: dfVpOK8LZeJLZHYmHdb1VdyRrACKpqoo
  signKey: /var/run/iam/certificates/ca.crt
