definitions:
  api.PageResponse:
    properties:
      list: { }
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
    type: object
  api.Response:
    properties:
      code:
        type: string
      data: { }
      msg:
        type: string
    type: object
  v1.DetailUserResponse:
    properties:
      alias:
        type: string
      create_time:
        type: string
      disabled:
        type: boolean
      email:
        type: string
      last_login_time:
        type: string
      name:
        type: string
      state:
        type: string
      type:
        type: string
    type: object
info:
  contact: { }
paths:
  /api/v1/users:
    get:
      description: list users
      parameters:
        - description: fuzzy search based on name
          in: query
          name: name
          type: string
        - description: fuzzy search based on alias
          in: query
          name: alias
          type: string
        - description: fuzzy search based on email
          in: query
          name: email
          type: string
        - description: query the page number
          in: query
          name: offset
          type: integer
        - description: query the page size number
          in: query
          name: limit
          type: integer
      responses:
        "200":
          description: '{"code": "000", "data": [...]} "users'
          schema:
            allOf:
              - $ref: '#/definitions/api.Response'
              - properties:
                  data:
                    allOf:
                      - $ref: '#/definitions/api.PageResponse'
                      - properties:
                          list:
                            items:
                              $ref: '#/definitions/v1.DetailUserResponse'
                            type: array
                        type: object
                type: object
      security:
        - Bearer: [ ]
      summary: list users
      tags:
        - Users
  /api/v1/users/{id}:
    get:
      description: get user detail
      parameters:
        - description: identifier of a user
          in: path
          name: id
          type: string
      responses:
        "200":
          description: '{"code": "000", "data": [...]} "user detail'
          schema:
            allOf:
              - $ref: '#/definitions/api.Response'
              - properties:
                  data:
                    $ref: '#/definitions/v1.DetailUserResponse'
                type: object
      security:
        - Bearer: [ ]
      summary: get user detail
      tags:
        - Users
swagger: "2.0"
