# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
output:
  path-prefix: ""
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - durationcheck
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nilnesserr
    - protogetter
    - reassign
    - recvcheck
    - revive
    - spancheck
    - testifylint
    - unconvert
    - zerologlint
  disable:
    - bodyclose
    - contextcheck
    - errchkjson
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unparam
  settings:
    bidichk:
      left-to-right-embedding: true
      right-to-left-embedding: true
      pop-directional-formatting: true
      left-to-right-override: true
      right-to-left-override: true
      left-to-right-isolate: true
      right-to-left-isolate: true
      first-strong-isolate: true
      pop-directional-isolate: true
    cyclop:
      max-complexity: 50
      package-average: 0
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    exhaustive:
      default-signifies-exhaustive: true
      ignore-enum-members: ""
      package-scope-only: false
    forbidigo:
      forbid:
        - pattern: fmt\.Print.*
        - pattern: fmt.Println.*
        - pattern: ginkgo\\.F.*
    funlen:
      lines: 150
      statements: 50
    gocognit:
      min-complexity: 30
    goconst:
      match-constant: true
      min-len: 3
      min-occurrences: 3
      numbers: false
      min: 3
      max: 3
      ignore-calls: true
    gocritic:
      enabled-checks:
        - truncateCmp
        - unnamedResult
        - ruleguard
      disabled-checks:
        - regexpMust
        - ifElseChain
        - exitAfterDefer
      enabled-tags:
        - performance
      disabled-tags:
        - experimental
      settings:
        captLocal:
          paramsOnly: true
        elseif:
          skipBalanced: true
        hugeParam:
          sizeThreshold: 80
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 32
          skipTestFuncs: true
        ruleguard:
          rules: ""
        truncateCmp:
          skipArchDependent: true
        underef:
          skipRecvDeref: true
        unnamedResult:
          checkExported: true
    gocyclo:
      min-complexity: 30
    godot:
      scope: declarations
      capital: false
    godox:
      keywords:
        - BUG
        - FIXME
        - OPTIMIZE
        - HACK
    goheader:
      # Supports two types 'const` and `regexp`.
      # Values can be used recursively.
      # Default: {}
      values:
        const:
          # Define here const type values in format k:v.
          # For example:
          COMPANY: WECODING
        regexp:
          # Define here regexp type values.
          # for example:
          AUTHOR: .*wecoding@\.yeah\.net
      template-path: hack/boilerplate.txt
    gomoddirectives:
      replace-allow-list:
        - google.golang.org/grpc
        - github.com/coding-hui/api
        - github.com/coding-hui/common
        - github.com/coding-hui/wecoding-sdk-go
      replace-local: true
      exclude-forbidden: false
      retract-allow-no-explanation: false
    gomodguard:
      allowed:
        modules:
          - gorm.io/gorm
          - gorm.io/driver/mysql
          - k8s.io/klog
          - k8s.io/klog/v2
          - k8s.io/component-base
          - k8s.io/apimachinery
        domains:
          - google.golang.org
          - gopkg.in
          - golang.org
          - github.com
          - go.uber.org
          - go.etcd.io
      blocked:
        modules:
          - github.com/pkg/errors:
              recommendations:
                - github.com/coding-hui/common/errors
              reason: '`github.com/coding-hui/common/errors` is the log package used by coding-hui projects.'
        versions:
          - github.com/MakeNowJust/heredoc:
              version: '> 2.0.9'
              reason: use the latest version
        local-replace-directives: false
    gosec:
      includes:
        - G401
        - G306
        - G101
      excludes:
        - G204
      severity: low
      confidence: low
      config:
        G101:
          entropy_threshold: "80.0"
          ignore_entropy: false
          pattern: (?i)example
          per_char_threshold: "3.0"
          truncate: "32"
        G306: "0600"
    govet:
      enable:
        - atomicalign
      disable:
        - shadow
      enable-all: false
      disable-all: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    importas:
      alias:
        - pkg: knative.dev/serving/pkg/apis/serving/v1
          alias: servingv1
        - pkg: knative.dev/serving/pkg/apis/autoscaling/v1alpha1
          alias: autoscalingv1alpha1
        - pkg: knative.dev/serving/pkg/apis/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/component-base/cli/flag
          alias: cliflag
        - pkg: github.com/coding-hui/common/meta/v1
          alias: metav1
      no-unaliased: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - (or|er)$
      reject:
        - github.com\/user\/package\/v4\.Type
    lll:
      tab-width: 1
    makezero:
      always: false
    misspell:
      locale: US
      ignore-rules:
        - someword
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 4
    nilnil:
      checked-types:
        - ptr
        - func
        - iface
        - map
        - chan
    nlreturn:
      block-size: 1
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    promlinter:
      strict: false
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
          severity: warning
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
      dot-import-whitelist:
        - fmt
      http-status-code-whitelist:
        - "200"
        - "400"
        - "404"
        - "500"
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: camel
          mapstructure: kebab
          xml: camel
          yaml: camel
        use-field-name: true
    testpackage:
      skip-regexp: (id|export|internal)_test\.go
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
    unparam:
      check-exported: false
    whitespace:
      multi-if: false
      multi-func: false
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
      ignore-package-globs:
        - encoding/*
        - github.com/pkg/*
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-assign-and-anything: false
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      force-err-cuddling: false
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - goconst
      - linters:
          - errorlint
        path: (pkg/validator/.*)\.go
      - linters:
          - forbidigo
        path: (cmd/.*|test/.*|tools/.*|internal/pump/pumps/.*)\.go
      - linters:
          - dupl
        path: (cmd/[a-z]*/.*|store/.*)\.go
      - linters:
          - gocritic
        text: (hugeParam:|rangeValCopy:)
      - linters:
          - tagliatelle
        path: (internal/.*/options|internal/pump|pkg/log/options.go|internal/authzserver|tools/)
      - linters:
          - deadcode
          - forbidigo
          - unused
          - varcheck
        path: (pkg/app/.*)\.go
      - linters:
          - lll
        source: '^//go:generate '
      - path: internal/iamctl/util/templates/templates.go
        linters:
          - gosec
      - path: tools/
        linters:
          - goconst
          - gosmopolitan
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: false
    goimports:
      local-prefixes:
        - github.com/coding-hui/iam
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
