server:
  port: 80
  servlet:
    context-path: /
  undertow:
    accesslog:
      enabled: true
      dir: log
      pattern: '%h %l %u %{User-Agent}i %t "%r" %s %b %D'

spring:
  application:
    name: wecoding-iam
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  cache:
    type: redis
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  liquibase:
    change-log: classpath:db/db.changelog-master.xml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wecoding_iam?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
  #    password: WeCoding319.
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 10s

logging:
  level:
    top.wecoding: debug
    org.springframework: warn

mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: top.wecoding.iam.server.pojo
  configuration:
    map-underscore-to-camel-case: true
