// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://iam.wecoding.top/",
        "contact": {
            "name": "coding-hui",
            "url": "https://github.com/coding-hui/iam",
            "email": "wecoding@yeah.net"
        },
        "license": {
            "name": "MIT",
            "url": "https://en.wikipedia.org/wiki/MIT_License"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/refresh-token": {
            "get": {
                "description": "RefreshToken",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "RefreshToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "refresh token",
                        "name": "RefreshToken",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token info",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.RefreshTokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "Login by user account and password",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "LoginSystem",
                "parameters": [
                    {
                        "description": "login request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.AuthenticateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token info",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.AuthenticateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/policies": {
            "get": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "List policies",
                "tags": [
                    "Policies"
                ],
                "summary": "ListPolicies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fuzzy search based on name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "query the page number",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "query the page size number",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "policies",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.PolicyList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Create a policy",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "CreatePolicy",
                "parameters": [
                    {
                        "description": "policy rule",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.CreatePolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create a nnw policy",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/policies/{instanceId}": {
            "get": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "GetByName a policy by name",
                "tags": [
                    "Policies"
                ],
                "summary": "GetPolicyInfo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of a policy",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Policy detail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.DetailPolicyResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Update a Policy",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "UpdatePolicy",
                "parameters": [
                    {
                        "description": "Policy rule",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.UpdatePolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update policy info",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "DeleteByInstanceId policy by instanceId",
                "tags": [
                    "Policies"
                ],
                "summary": "DeletePolicy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of a policy",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Policy successfully deleted",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/resources": {
            "get": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "List resources",
                "tags": [
                    "Resource"
                ],
                "summary": "ListResources",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fuzzy search based on name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "query the page number",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "query the page size number",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "resources",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.ResourceList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Create resource",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Resource"
                ],
                "summary": "CreateResource",
                "parameters": [
                    {
                        "description": "resource info",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.CreateResourceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "create a new resource",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/resources/{instanceId}": {
            "get": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "GetByName resource info",
                "tags": [
                    "Resource"
                ],
                "summary": "GetResourceInfo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of a resource",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "resource detail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.DetailResourceResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Update resource",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Resource"
                ],
                "summary": "UpdateResource",
                "parameters": [
                    {
                        "description": "resource info",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.UpdateResourceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update resource info",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "DeleteByInstanceId resource",
                "tags": [
                    "Resource"
                ],
                "summary": "DeleteResource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of a resource",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delete resource",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/roles": {
            "get": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "List role",
                "tags": [
                    "Roles"
                ],
                "summary": "ListRoles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fuzzy search based on name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "query the page number",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "query the page size number",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "roles",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1alpha1.RoleBase"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Create role",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "CreateRole",
                "parameters": [
                    {
                        "description": "role info",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.CreateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "create a new role",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/roles/{instanceId}": {
            "get": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "GetByName role info",
                "tags": [
                    "Roles"
                ],
                "summary": "GetRoleInfo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of a role",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "role detail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.DetailRoleResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Update role",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "UpdateRole",
                "parameters": [
                    {
                        "description": "role info",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.UpdateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update role info",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "DeleteByInstanceId role",
                "tags": [
                    "Roles"
                ],
                "summary": "DeleteRole",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of a role",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delete role",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/roles/{instanceId}/assign": {
            "post": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Batch assign role",
                "tags": [
                    "Roles"
                ],
                "summary": "BatchAssignRole",
                "parameters": [
                    {
                        "description": "batch assign role request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.BatchAssignRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "assign role",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/roles/{instanceId}/revoke": {
            "post": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Revoke role",
                "tags": [
                    "Roles"
                ],
                "summary": "RevokeRole",
                "parameters": [
                    {
                        "description": "revoke role request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.RevokeRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "revoke role",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "List users",
                "tags": [
                    "Users"
                ],
                "summary": "ListUsers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fuzzy search based on name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "fuzzy search based on alias",
                        "name": "alias",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "fuzzy search based on email",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "query the page number",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "query the page size number",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "users",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.UserList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Create user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "CreateUser",
                "parameters": [
                    {
                        "description": "user info",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "create a nnw user",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{instanceId}": {
            "get": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "GetByName user info",
                "tags": [
                    "Users"
                ],
                "summary": "GetUserInfo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of a user",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user detail",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.UserBase"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Update user info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "UpdateUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of a user",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "user info",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1alpha1.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update user info",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "DeleteByInstanceId user",
                "tags": [
                    "Users"
                ],
                "summary": "DeleteUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of a user",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delete user",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{instanceId}/roles": {
            "get": {
                "security": [
                    {
                        "BearerTokenAuth": []
                    }
                ],
                "description": "Get user roles",
                "tags": [
                    "Users"
                ],
                "summary": "GetUserRoles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of a user",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user roles",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1alpha1.RoleList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Check service is running",
                "tags": [
                    "System"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code defines the business error code.",
                    "type": "integer"
                },
                "data": {
                    "description": "Data return data object"
                },
                "msg": {
                    "description": "Msg contains the detail of this message.\nThis message is suitable to be exposed to external",
                    "type": "string"
                },
                "reference": {
                    "description": "Reference returns the reference document which maybe useful to solve this error.",
                    "type": "string"
                },
                "success": {
                    "description": "Success request is successful",
                    "type": "boolean"
                }
            }
        },
        "v1.Extend": {
            "type": "object",
            "additionalProperties": true
        },
        "v1.ObjectMeta": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt is a timestamp representing the server time when this object was\ncreated. It is not guaranteed to be set in happens-before order across separate operations.\nClients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system.\nRead-only.\nNull for lists.",
                    "type": "string"
                },
                "extend": {
                    "description": "Extend store the fields that need to be added, but do not want to add a new table column, will not be stored in\ndb.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.Extend"
                        }
                    ]
                },
                "id": {
                    "description": "ID is the unique in time and space value for this object. It is typically generated by\nthe storage on successful creation of a resource and is not allowed to change on PUT\noperations.\n\nPopulated by the system.\nRead-only.",
                    "type": "integer"
                },
                "instanceId": {
                    "description": "InstanceID defines a string type resource identifier,\nuse prefixed to distinguish resource types, easy to remember, Url-friendly.",
                    "type": "string"
                },
                "name": {
                    "description": "Required: true\nName must be unique. Is required when creating resources.\nName is primarily intended for creation idempotence and configuration\ndefinition.\nIt will be generated automated only if Name is not specified.\nCannot be updated.",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "UpdatedAt is a timestamp representing the server time when this object was updated.\nClients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system.\nRead-only.\nNull for lists.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.Action": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.AssignRoleRequest": {
            "type": "object",
            "required": [
                "instanceId"
            ],
            "properties": {
                "instanceId": {
                    "description": "InstanceID role instanceID.",
                    "type": "string"
                },
                "targets": {
                    "description": "Targets target resource instanceIds.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "v1alpha1.AuthenticateRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.AuthenticateResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "AccessToken is the token that authorizes and authenticates\nthe requests.",
                    "type": "string"
                },
                "expires_in": {
                    "description": "ExpiresIn is the optional expiration second of the access token.",
                    "type": "integer"
                },
                "refresh_token": {
                    "description": "RefreshToken is a token that's used by the application\n(as opposed to the user) to refresh the access token\nif it expires.",
                    "type": "string"
                },
                "token_type": {
                    "description": "TokenType is the type of token.\nThe Type method returns either this or \"Bearer\", the default.",
                    "type": "string"
                },
                "user": {
                    "description": "User user info",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.UserBase"
                        }
                    ]
                }
            }
        },
        "v1alpha1.BatchAssignRoleRequest": {
            "type": "object",
            "required": [
                "instanceIds"
            ],
            "properties": {
                "instanceIds": {
                    "description": "InstanceIds role instanceIds.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targets": {
                    "description": "Targets target resource instanceIds.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "v1alpha1.CreatePolicyRequest": {
            "type": "object",
            "required": [
                "name",
                "statements",
                "subjects",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 1
                },
                "meta": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "statements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.Statement"
                    }
                },
                "status": {
                    "type": "string"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.CreateResourceRequest": {
            "type": "object",
            "required": [
                "actions",
                "api",
                "method",
                "name",
                "type"
            ],
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.Action"
                    }
                },
                "api": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.CreateRoleRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 1
                }
            }
        },
        "v1alpha1.CreateUserRequest": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "alias": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "userType": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.DetailPolicyResponse": {
            "type": "object",
            "properties": {
                "adapter": {
                    "description": "casbin required",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "metadata": {
                    "description": "Standard object's metadata.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.ObjectMeta"
                        }
                    ]
                },
                "model": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "policyRules": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.ResourceBase"
                    }
                },
                "statements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.Statement"
                    }
                },
                "status": {
                    "type": "string"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.DetailResourceResponse": {
            "type": "object",
            "required": [
                "actions",
                "api",
                "method",
                "type"
            ],
            "properties": {
                "actions": {
                    "description": "Actions resource access mode.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.Action"
                    }
                },
                "api": {
                    "description": "Type unique identification of resource API.",
                    "type": "string"
                },
                "description": {
                    "description": "Description resource description.",
                    "type": "string"
                },
                "metadata": {
                    "description": "Standard object's metadata.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.ObjectMeta"
                        }
                    ]
                },
                "method": {
                    "description": "Method resource method.",
                    "type": "string"
                },
                "type": {
                    "description": "Type resource type.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.DetailRoleResponse": {
            "type": "object",
            "required": [
                "owner"
            ],
            "properties": {
                "description": {
                    "description": "Description tenant description.",
                    "type": "string"
                },
                "disabled": {
                    "description": "Disabled tenant state.",
                    "type": "boolean"
                },
                "metadata": {
                    "description": "Standard object's metadata.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.ObjectMeta"
                        }
                    ]
                },
                "owner": {
                    "description": "Owner tenant owner name.",
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.UserBase"
                    }
                }
            }
        },
        "v1alpha1.PolicyBase": {
            "type": "object",
            "properties": {
                "adapter": {
                    "description": "casbin required",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "metadata": {
                    "description": "Standard object's metadata.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.ObjectMeta"
                        }
                    ]
                },
                "model": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "policyRules": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "statements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.Statement"
                    }
                },
                "status": {
                    "type": "string"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.PolicyList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.PolicyBase"
                    }
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "v1alpha1.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.ResourceBase": {
            "type": "object",
            "required": [
                "actions",
                "api",
                "method",
                "type"
            ],
            "properties": {
                "actions": {
                    "description": "Actions resource access mode.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.Action"
                    }
                },
                "api": {
                    "description": "Type unique identification of resource API.",
                    "type": "string"
                },
                "description": {
                    "description": "Description resource description.",
                    "type": "string"
                },
                "metadata": {
                    "description": "Standard object's metadata.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.ObjectMeta"
                        }
                    ]
                },
                "method": {
                    "description": "Method resource method.",
                    "type": "string"
                },
                "type": {
                    "description": "Type resource type.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.ResourceList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.ResourceBase"
                    }
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "v1alpha1.RevokeRoleRequest": {
            "type": "object",
            "required": [
                "instanceId"
            ],
            "properties": {
                "instanceId": {
                    "description": "InstanceID role instanceID.",
                    "type": "string"
                },
                "targets": {
                    "description": "Targets target resource instanceIds.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "v1alpha1.RoleBase": {
            "type": "object",
            "required": [
                "owner"
            ],
            "properties": {
                "description": {
                    "description": "Description tenant description.",
                    "type": "string"
                },
                "disabled": {
                    "description": "Disabled tenant state.",
                    "type": "boolean"
                },
                "metadata": {
                    "description": "Standard object's metadata.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.ObjectMeta"
                        }
                    ]
                },
                "owner": {
                    "description": "Owner tenant owner name.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.RoleList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.RoleBase"
                    }
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "v1alpha1.Statement": {
            "type": "object",
            "required": [
                "actions",
                "effect",
                "resource",
                "resourceIdentifier"
            ],
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "effect": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "resourceIdentifier": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.UpdatePolicyRequest": {
            "type": "object",
            "required": [
                "statements",
                "subjects",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 1
                },
                "meta": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "statements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.Statement"
                    }
                },
                "status": {
                    "type": "string"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.UpdateResourceRequest": {
            "type": "object",
            "required": [
                "actions",
                "api",
                "method",
                "name",
                "type"
            ],
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.Action"
                    }
                },
                "api": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.UpdateRoleRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.UpdateUserRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "alias": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 1
                },
                "email": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.UserBase": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "lastLoginTime": {
                    "type": "string"
                },
                "metadata": {
                    "description": "Standard object's metadata.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.ObjectMeta"
                        }
                    ]
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "tenantId": {
                    "type": "integer"
                },
                "userType": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.UserList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.UserBase"
                    }
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerTokenAuth": {
            "description": "Set Bearer token in the request header",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1alpha",
	Host:             "localhost:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "IAM API",
	Description:      "IAM ApiService API Doc.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
