definitions:
  api.Response:
    properties:
      code:
        description: Code defines the business error code.
        type: integer
      data:
        description: Data return data object
      msg:
        description: |-
          Msg contains the detail of this message.
          This message is suitable to be exposed to external
        type: string
      reference:
        description: Reference returns the reference document which maybe useful to
          solve this error.
        type: string
      success:
        description: Success request is successful
        type: boolean
      total:
        description: Total total of page
        type: integer
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      description: check service is running
      responses:
        "200":
          description: '{"code": "000", "data": [...]}'
          schema:
            $ref: '#/definitions/api.Response'
      summary: check service is running
      tags:
      - System
swagger: "2.0"
