// Copyright (c) 2023 coding-hui. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

package driver

import (
	"context"

	"github.com/sirupsen/logrus"

	"go.opentelemetry.io/otel/trace"
)

// Registry is the central interface that provides access to all
// application services and infrastructure components.
// It follows the Ory Registry pattern with sync.Once lazy initialization.
//
// Registry implementations are generated by wire or similar DI tools.
// The concrete implementation is RegistryDefault in registry_default.go.
type Registry interface {
	// Infrastructure
	Config() *Config
	Logger() *logrus.Logger
	Tracer() trace.Tracer

	// Identity (implemented in L1)
	IdentityPool() any
	PrivilegedIdentityPool() any
	IdentityManager() any

	// Session (implemented in L1)
	SessionPool() any
	PrivilegedSessionPool() any
	SessionManager() any

	// Role (implemented in L2)
	RolePool() any
	PrivilegedRolePool() any
	RoleManager() any

	// Policy (implemented in L2)
	PolicyPool() any
	PrivilegedPolicyPool() any
	PolicyManager() any

	// AuthZ (implemented in L2)
	AuthzEngine() any

	// Token (implemented in L3)
	TokenPool() any
	TokenManager() any

	// AuthN (implemented in L1)
	Authenticator() any

	// MFA (implemented in L3)
	MFAManager() any

	// Audit (implemented in L3)
	AuditRecorder() any
	AuditPool() any
	AuditManager() any

	// Lockout (implemented in L3)
	LockoutManager() any

	// Webhook (implemented in L3)
	WebhookManager() any

	// Persistence
	Persister() Persister
	MigrateUp(ctx context.Context) error

	// Cache
	Cache() Cache

	// HTTP - returns an HTTP handler interface to avoid import cycle
	Router() HTTPHandler

	// Notification (implemented in L3)
	NotificationSender() any

	// Init initializes all services
	Init(ctx context.Context) error
}

// HTTPHandler is an interface abstracting HTTP server to avoid import cycle.
// The actual implementation is typically in the api package.
type HTTPHandler interface {
	// Group creates a new route group with the given prefix.
	Group(relativePath string, middleware ...any) HTTPGroup
	GET(relativePath string, handlers ...any)
	POST(relativePath string, handlers ...any)
	PUT(relativePath string, handlers ...any)
	PATCH(relativePath string, handlers ...any)
	DELETE(relativePath string, handlers ...any)
	Run(addr ...string) error
}

// HTTPGroup is an interface abstracting route groups.
type HTTPGroup interface {
	Handle(httpMethod, relativePath string, handlers ...any)
	GET(relativePath string, handlers ...any)
	POST(relativePath string, handlers ...any)
	PUT(relativePath string, handlers ...any)
	PATCH(relativePath string, handlers ...any)
	DELETE(relativePath string, handlers ...any)
	Use(middleware ...any)
}

// Persister is the database persistence interface.
// Actual implementation is in persistence package.
type Persister interface {
	Transaction(ctx context.Context, fn func(ctx context.Context) error) error
	Close(ctx context.Context) error
}

// Cache is the cache interface.
// Actual implementation is in cache package.
type Cache interface {
	Get(ctx context.Context, key string) ([]byte, error)
	Set(ctx context.Context, key string, value []byte, ttl int64) error
	Delete(ctx context.Context, key string) error
	Keys(ctx context.Context, pattern string) ([]string, error)
	Ping(ctx context.Context) error
}
