apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iam.consoleFullname" . }}
  labels:
    {{- include "iam.consoleLabels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- .Files.Get .Values.console.configFile | nindent 4}}
