#!/usr/bin/env bash

# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

# IAM 项目源码根目录（解析为绝对路径，避免相对路径问题）
IAM_ROOT=$(cd $(dirname "${BASH_SOURCE[0]}")/../.. && pwd)

# 生成文件存放目录
LOCAL_OUTPUT_ROOT="${IAM_ROOT}/${OUT_DIR:-_output}"

if [[ "$(uname -s)" == "Darwin" ]]; then
  readonly IAM_DATA_DIR="${HOME}/.iam/data"       # 各组件数据目录
  readonly IAM_INSTALL_DIR="${HOME}/.iam"         # 二进制和静态文件
  readonly IAM_CONFIG_DIR="${HOME}/.iam/conf"      # 配置文件
  readonly IAM_LOG_DIR="${HOME}/.iam/logs"        # 日志文件
else
  readonly IAM_DATA_DIR=${IAM_DATA_DIR:-/data/iam}
  readonly IAM_INSTALL_DIR=${IAM_INSTALL_DIR:-/opt/iam}
  readonly IAM_CONFIG_DIR=${IAM_CONFIG_DIR:-/etc/iam}
  readonly IAM_LOG_DIR=${IAM_LOG_DIR:-/var/log/iam}
fi

readonly ENV_FILE=${IAM_ROOT}/hack/install/environment.sh

readonly PASSWORD=${PASSWORD:-'iam59!z$'}

# Linux 系统用户（仅 Linux 使用，macOS 不需要）
readonly LINUX_USERNAME=${LINUX_USERNAME:-going}
readonly LINUX_PASSWORD=${LINUX_PASSWORD:-${PASSWORD}}

# MariaDB 配置信息
readonly MARIADB_ADMIN_USERNAME=${MARIADB_ADMIN_USERNAME:-root}
readonly MARIADB_ADMIN_PASSWORD=${MARIADB_ADMIN_PASSWORD:-${PASSWORD}}
readonly MARIADB_HOST=${MARIADB_HOST:-127.0.0.1:3306}
readonly MARIADB_DATABASE=${MARIADB_DATABASE:-iam}
readonly MARIADB_USERNAME=${MARIADB_USERNAME:-iam}
readonly MARIADB_PASSWORD=${MARIADB_PASSWORD:-${PASSWORD}}

# Redis 配置信息
readonly REDIS_HOST=${REDIS_HOST:-127.0.0.1}
readonly REDIS_PORT=${REDIS_PORT:-6379}
readonly REDIS_USERNAME=${REDIS_USERNAME:-''}
readonly REDIS_PASSWORD=${REDIS_PASSWORD:-${PASSWORD}}

# MongoDB 配置
readonly MONGO_ADMIN_USERNAME=${MONGO_ADMIN_USERNAME:-root}
readonly MONGO_ADMIN_PASSWORD=${MONGO_ADMIN_PASSWORD:-${PASSWORD}}
readonly MONGO_HOST=${MONGO_HOST:-127.0.0.1}
readonly MONGO_PORT=${MONGO_PORT:-27017}
readonly MONGO_USERNAME=${MONGO_USERNAME:-iam}
readonly MONGO_PASSWORD=${MONGO_PASSWORD:-${PASSWORD}}

# iam-apiserver 配置
readonly IAM_APISERVER_HOST=${IAM_APISERVER_HOST:-127.0.0.1}
readonly IAM_APISERVER_GRPC_BIND_ADDRESS=${IAM_APISERVER_GRPC_BIND_ADDRESS:-0.0.0.0}
readonly IAM_APISERVER_GRPC_BIND_PORT=${IAM_APISERVER_GRPC_BIND_PORT:-8081}
readonly IAM_APISERVER_INSECURE_BIND_ADDRESS=${IAM_APISERVER_INSECURE_BIND_ADDRESS:-127.0.0.1}
readonly IAM_APISERVER_INSECURE_BIND_PORT=${IAM_APISERVER_INSECURE_BIND_PORT:-8080}
readonly IAM_APISERVER_SECURE_BIND_ADDRESS=${IAM_APISERVER_SECURE_BIND_ADDRESS:-0.0.0.0}
readonly IAM_APISERVER_SECURE_BIND_PORT=${IAM_APISERVER_SECURE_BIND_PORT:-8443}
readonly IAM_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE=${IAM_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE:-${IAM_CONFIG_DIR}/cert/iam-apiserver.pem}
readonly IAM_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE=${IAM_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE:-${IAM_CONFIG_DIR}/cert/iam-apiserver-key.pem}

# iam-authz-server 配置
readonly IAM_AUTHZ_SERVER_HOST=${IAM_AUTHZ_SERVER_HOST:-127.0.0.1}
readonly IAM_AUTHZ_SERVER_INSECURE_BIND_ADDRESS=${IAM_AUTHZ_SERVER_INSECURE_BIND_ADDRESS:-127.0.0.1}
readonly IAM_AUTHZ_SERVER_INSECURE_BIND_PORT=${IAM_AUTHZ_SERVER_INSECURE_BIND_PORT:-9090}
readonly IAM_AUTHZ_SERVER_SECURE_BIND_ADDRESS=${IAM_AUTHZ_SERVER_SECURE_BIND_ADDRESS:-0.0.0.0}
readonly IAM_AUTHZ_SERVER_SECURE_BIND_PORT=${IAM_AUTHZ_SERVER_SECURE_BIND_PORT:-9443}
readonly IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_CERT_FILE=${IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_CERT_FILE:-${IAM_CONFIG_DIR}/cert/iam-authz-server.pem}
readonly IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE=${IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE:-${IAM_CONFIG_DIR}/cert/iam-authz-server-key.pem}
readonly IAM_AUTHZ_SERVER_CLIENT_CA_FILE=${IAM_AUTHZ_SERVER_CLIENT_CA_FILE:-${CA_FILE}}
readonly IAM_AUTHZ_SERVER_RPCSERVER=${IAM_AUTHZ_SERVER_RPCSERVER:-${IAM_APISERVER_HOST}:${IAM_APISERVER_GRPC_BIND_PORT}}

# iam-pump 配置
readonly IAM_PUMP_HOST=${IAM_PUMP_HOST:-127.0.0.1}
readonly IAM_PUMP_COLLECTION_NAME=${IAM_PUMP_COLLECTION_NAME:-iam_analytics}
readonly IAM_PUMP_MONGO_URL=${IAM_PUMP_MONGO_URL:-mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${IAM_PUMP_COLLECTION_NAME}?authSource=${IAM_PUMP_COLLECTION_NAME}}

# iam-watcher 配置
readonly IAM_WATCHER_HOST=${IAM_WATCHER_HOST:-127.0.0.1}

# iamctl 配置
readonly CONFIG_USER_USERNAME=${CONFIG_USER_USERNAME:-admin}
readonly CONFIG_USER_PASSWORD=${CONFIG_USER_PASSWORD:-Admin@2021}
readonly CONFIG_USER_CLIENT_CERTIFICATE=${CONFIG_USER_CLIENT_CERTIFICATE:-${HOME}/.iam/cert/admin.pem}
readonly CONFIG_USER_CLIENT_KEY=${CONFIG_USER_CLIENT_KEY:-${HOME}/.iam/cert/admin-key.pem}
readonly CONFIG_SERVER_ADDRESS=${CONFIG_SERVER_ADDRESS:-${IAM_APISERVER_HOST}:${IAM_APISERVER_SECURE_BIND_PORT}}
readonly CONFIG_SERVER_CERTIFICATE_AUTHORITY=${CONFIG_SERVER_CERTIFICATE_AUTHORITY:-${CA_FILE}}

# CA 证书路径
readonly CA_FILE=${CA_FILE:-${IAM_CONFIG_DIR}/cert/ca.pem}
