# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iam.apiServerFullname" . }}
  labels:
    {{- include "iam.apiServerLabels" . | nindent 4 }}
data:
  iam-apiserver.yaml: |
    server:
      mode: debug # server mode: release, debug, test
      healthz: true # If enabled, the /healthz route is installed. default value is true
      middlewares: recovery,logger,secure,nocache,cors,dump
      max-ping-count: 3

    grpc:
      bind-address: 0.0.0.0
      bind-port: 8081

    insecure:
      bind-address: 0.0.0.0
      bind-port: 8080

    secure:
      bind-address: 0.0.0.0
      bind-port: 8443
      tls:
        #cert-dir: .iam/cert # TLS cert file dir, default /var/run/iam
        #pair-name: iam # TLS private key name, default iam
        cert-key:
          cert-file: ${IAM_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE}
          private-key-file: ${IAM_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE}

    mysql:
      host: 127.0.0.1:3306
      username: root
      password: root
      database: iam_1
      max-idle-connections: 100
      max-open-connections: 100
      max-connection-life-time: 10s
      log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

    redis:
      host: 127.0.0.1:6379
      port: 6379
      password:

    jwt:
      realm: JWT
      key: dfVpOK8LZeJLZHYmHdb1VdyRrACKpqoo
      timeout: 24h
      max-refresh: 24h

    log:
      name: apiserver
      development: false
      level: info
      format: console
      enable-color: true
      disable-caller: false
      disable-stacktrace: false
      output-paths: /var/log/iam-apiserver.log,stdout
      error-output-paths: /var/log/iam-apiserver.error.log

    feature:
      enable-metrics: true
      profiling: true
