# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

version: "3.9"

services:

  api-server:
    image: devops-wecoding-docker.pkg.coding.net/wecoding/docker-repo/iam-apiserver-amd64:v0.7-45-g511eae4
    pull_policy: always
    hostname: iam-aiserver
    container_name: iam-apiserver
    command: iam-apiserver --datastore-url="root:123456@tcp(db:3306)/iam_1?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms"
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db
    networks:
      network:
        ipv4_address: 177.7.0.12

  db:
    image: mysql
    container_name: iam-db
    hostname: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      network:
        ipv4_address: 177.7.0.13

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'
