# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

version: "3.9"

services:

  api-server:
    image: devops-wecoding-docker.pkg.coding.net/wecoding/docker-repo/iam-apiserver-amd64:v0.7-45-g511eae4
    pull_policy: always
    hostname: iam-aiserver
    container_name: iam-apiserver
    restart: always
    environment:
      IAM_APISERVER_GRPC_BIND_ADDRESS: 0.0.0.0
      IAM_APISERVER_GRPC_BIND_PORT: 8020
      IAM_APISERVER_INSECURE_BIND_ADDRESS: 0.0.0.0
      IAM_APISERVER_INSECURE_BIND_PORT: 8000
      IAM_APISERVER_SECURE_BIND_ADDRESS: 0.0.0.0
      IAM_APISERVER_SECURE_BIND_PORT: 8443
      IAM_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE: /var/run/iam
      IAM_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE:  /var/run/iam
      MARIADB_HOST: db:3306
      MARIADB_USERNAME: root
      MARIADB_DATABASE: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      IAM_LOG_DIR: /var/log/iam
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db
    networks:
      network:
        ipv4_address: 177.7.0.12

  db:
    image: mysql
    container_name: iam-db
    hostname: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      network:
        ipv4_address: 177.7.0.13

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'
