# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

version: "3.9"

services:

  apiserver:
    image: wecoding/apiserver:latest
    hostname: apiserver
    container_name: apiserver
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ../../conf:/etc/iam

  db:
    image: mysql
    container_name: iam-db
    hostname: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10

  redis:
    image: redis
    container_name: iam-redis
    hostname: redis
    command: redis-server --appendonly yes
    restart: always
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  mysql_data:
