# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

apiVersion: v1
credentials:
  #token: # JWT Token
  username: ${CONFIG_USER_USERNAME} # iam 用户名
  password: ${CONFIG_USER_PASSWORD} # iam 密码
  #accessKeyId: # 密钥 ID
  #secretAccessKey: # 密钥 Key
  clientCertificate: ${CONFIG_USER_CLIENT_CERTIFICATE} # 用于 TLS 的客户端证书文件路径
  clientKey: ${CONFIG_USER_CLIENT_KEY} # 用于 TLS 的客户端 key 文件路径
  #clientCertificateData:
  #clientKeyData:

server:
  endpoint: http://${CONFIG_SERVER_ADDRESS} # iam api-server 地址
  timeout: 10s # 请求 api-server 超时时间
  #maxRetries: # 最大重试次数，默认为 0
  #retryInterval: # 重试间隔，默认为 1s
  #tlsServerName: # TLS 服务器名称
  #insecureSkipTLSVerify: # 设置为 true 表示跳过 TLS 安全验证模式，将使得 HTTPS 连接不安全
  #certificateAuthority: ${CONFIG_SERVER_CERTIFICATE_AUTHORITY} # 用于 CA 授权的 cert 文件路径
  #certificateAuthorityData:
  authzEndpoint: ${CONFIG_AUTHZ_ENDPOINT} # iam authz-server 地址
