apiVersion: v1
kind: Service
metadata:
  name: wecoding-iam
  namespace: wecoding-system
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: wecoding-iam
