name: Docker Image CI

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
    paths-ignore:
      - 'examples/**'
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ''
  REGISTRY_PREFIX: wecoding

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print commit ID
      run: echo "The commit ID is ${{ github.sha }}"

    - name: Set ROOT_DIR environment variable
      run: echo "ROOT_DIR=$(pwd)" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      uses: docker/login-action@v2.2.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ env.REGISTRY }}
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PWD }}

    - name: Build and push Docker images
      run: make image.push REGISTRY_PREFIX=${{ env.REGISTRY_PREFIX }}
