# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

# This is a basic workflow to help you get started with Actions

name: Sync to Gitee

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "go-0.x" branch
  push:
    branches:
      - "go-0.x"
      - "develop"
    tags:
      - "*"
  pull_request:
    branches:
      - "go-0.x"
      - "develop"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Mirror Github to Gitee
        uses: Yikun/hub-mirror-action@v1.2
        with:
          src: github/coding-hui
          dst: gitee/coder-hui
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          timeout: 600
          debug: true
          force_update: true
          static_list: "iam"
          clone_style: "ssh"
