# Copyright (c) 2023 coding-hui. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

name: Release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
    paths-ignore:
      - 'examples/**'
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch: {}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set ROOT_DIR environment variable
        run: |
          echo "ROOT_DIR=$(pwd)" >> $GITHUB_ENV
          ls -ls

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Install tools
        run: |
          go install github.com/coding-hui/addlicense@latest
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            VERSION=latest
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use 2>/dev/null || true
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push \
            -t ${{ vars.REGISTRY_PREFIX }}/apiserver:$VERSION \
            -f installer/dockerfile/apiserver/Dockerfile .
